fix: add fuse

diff --git a/.github/workflows/electron-release.yml b/.github/workflows/electron-release.yml
--- a/.github/workflows/electron-release.yml
+++ b/.github/workflows/electron-release.yml
@@ -24,6 +24,11 @@ jobs:
 
       - uses: actions/checkout@v4
       
+      - name: Install and Load fuse
+        run: |
+          pacman -Syu fuse2 fuse3 --noconfirm
+          modprobe fuse || echo "Unable to load fuse, ensure it's supported by the host"
+      
       - name: Install Flatpak SDK and Dependencies
         run: |
           pacman -S flatpak --noconfirm
